version: "3"

services:
    # This service starts a static resource web server that will be used by clients
    nginx:
        image: whiteboard/nginx:latest
        build: ./nginx
        ports:
            - "80:80"
        networks:
            main:
                aliases:
                    - nginx
    frontend:
        image: whiteboard/frontend:latest
        build: ./frontend/whiteboard-frontend
        networks:
            main:
                aliases:
                    - web
        ports:
            - "8080:8080"
        volumes:
            - .:/usr/src/app/app
            - /usr/src/app/app/node_modules
    backend:
        hostname: collaborative_whiteboard_api
        image: whiteboard/backend:latest
        build: ./backend
        networks:
            main:
                aliases:
                    - api
        ports:
        - "4000:4000"
        expose:
        - 4000
    db:
        image: mongo:latest
        networks:
            main:
                aliases:
                    - db
        ports:
            - '27017:27017'
        expose:
            - 27017
        volumes:
            - dbdata6:/data/db

volumes:
    dbdata6:

networks:
    main:
        